INPUT_COLUMN_TOOLTIPS = {
    "contract_values": {
        "agreement_year": "Contract year these reference values apply to.",
        "cppf": "Fixed component of the Capability Payment Price. CPP is calculated as CPPF plus CPPPIF.",
        "cpppif": "Interconnection/payment component of the Capability Payment Price. Use the final applicable contract value for the year.",
        "ddd": "Design Dmax Duration: the design discharge duration used to convert duration energy into monthly contract capability.",
        "ta": "Threshold Availability. Availability liquidated damages may apply when Facility Availability falls below this level.",
        "rer": "Replacement Energy Rate used in the liquidated damages rate calculation.",
        "ge": "Guaranteed Efficiency for the billing period. Efficiency liquidated damages may apply when Actual Efficiency is below this value.",
        "design_dmax": "Design maximum discharge capability of the facility.",
        "design_duration_energy": "Design Duration Energy: discharge energy the facility can deliver at Design Dmax over the design duration.",
        "annual_duration_energy_degradation_rate": "Annual degradation factor applied to Design Duration Energy when deriving expected DDE.",
        "design_charge_energy": "Design Charge Energy the facility is expected to accept during the design charge duration.",
        "grid_system_waiting_period_hours": "Annual Grid System Event waiting-period allowance used before GSE hours reduce PRA.",
        "force_majeure_waiting_period_hours": "Annual PREPA Force Majeure waiting-period allowance used before PFM hours reduce PRA.",
        "scheduled_maintenance_allowance_hours": "Annual scheduled maintenance outage allowance. Excess permitted outage hours are treated as unavailable hours.",
        "source_reference": "Contract, amendment, worksheet, or source note supporting this value.",
        "notes": "Short context for assumptions, overrides, or review notes.",
    },
    "yearly_inputs": {
        "agreement_year": "Contract year these yearly operating inputs apply to.",
        "dde": "Degraded Duration Energy for the agreement year. It starts from Design Duration Energy and reflects contract degradation and qualifying performance-test adjustments.",
        "tr": "Tested Result used for annual Monthly Contract Capability before a same-year performance test becomes effective.",
        "gc": "Guaranteed Capability for capability liquidated damages. If blank, the current calculator treats DDE as the default capability basis.",
        "source_reference": "Source document, meter package, test report, or worksheet supporting the yearly value.",
        "notes": "Short context for assumptions, overrides, or review notes.",
    },
    "monthly_inputs": {
        "timestamp_month": "Billing month represented by this row.",
        "agreement_year": "Contract year that controls this billing month.",
        "other_adj": "Other Payment Adjustments owed to PREPA under the agreement. Exclude calculator-generated ALD, CLD, and ELD unless intentionally double-counting.",
        "bphrs": "Total hours in the billing period.",
        "pohrs": "Permitted outage hours when the facility was unavailable to deliver Adjusted Duration Energy or accept Charge Energy.",
        "unavhrs": "Unavailable hours affecting energy delivery or charge acceptance, excluding hours already counted as permitted outage hours.",
        "unavprodhrs": "Hours the facility could provide energy but could not provide other Product due to an inhibiting event.",
        "gse": "Grid System Event hours for the billing period, subject to the annual Grid System Waiting Period.",
        "pfm": "Force Majeure affecting PREPA hours for the billing period, subject to the annual Force Majeure Waiting Period.",
        "ip": "Hours tied to events where Resource Provider may recover insurance proceeds for PREPA Risk Events.",
        "source_reference": "Source document, meter package, operator note, or worksheet supporting the monthly value.",
        "notes": "Short context for assumptions, adjustments, or review notes.",
    },
    "monthly_performance_guarantee": {
        "timestamp_month": "Billing month for the efficiency guarantee inputs.",
        "agreement_year": "Contract year that controls this billing month.",
        "ce": "Charge Energy for the billing period, used in Actual Efficiency and ELD calculations.",
        "de": "Discharge Energy for the billing period, used in Actual Efficiency and ELD calculations.",
        "ae_beg": "Stored/available energy adjustment at the beginning of the billing period for Actual Efficiency.",
        "ae_end": "Stored/available energy adjustment at the end of the billing period for Actual Efficiency.",
        "source_reference": "Meter source, report, or worksheet supporting the efficiency inputs.",
        "notes": "Short context for assumptions, adjustments, or review notes.",
    },
    "performance_tests": {
        "test_id": "Unique identifier for the performance test event.",
        "agreement_year": "Contract year associated with the test.",
        "test_type": "Type of performance test, such as PREPA test, Resource Provider test, retest, cure test, or ramp-rate test.",
        "test_date": "Date the performance test occurred. The calculator uses approved tests to determine later MCC and LD effects.",
        "requested_by": "Party that requested or initiated the test.",
        "tde": "Tested Duration Energy demonstrated by the performance test.",
        "measured_ramp_rate": "Ramp rate demonstrated during the test. Failure to meet the guaranteed ramp rate may create outage consequences.",
        "certified_by": "Person or entity certifying the test result.",
        "prepa_approved": "Whether PREPA approved the test result for calculator use.",
        "approval_date": "Date PREPA approved the test result, if applicable.",
        "cure_or_retest_date": "Date a cure or retest resolved a failed performance test condition.",
        "replaces_test_id": "Prior test this row supersedes or cures.",
        "ramp_failure_caused_outage": "Marks whether a ramp-rate failure caused a Non-Scheduled Outage that should be tracked.",
        "outage_start": "Start of the outage tied to a ramp-rate failure.",
        "outage_end": "End of the outage tied to a ramp-rate failure.",
        "outage_equivalent_unavhrs": "Unavailable-hour impact from the ramp-rate outage; reflect this in monthly availability inputs when applicable.",
        "source_reference": "Test report, approval record, or source note supporting this row.",
        "notes": "Short context for assumptions, approval status, or review notes.",
    },
}
